require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "help",
    "javascript",
    "typescript",
    "tsx",
    "css",
    "html",
    "astro",
    "json",
    "toml",
    "yaml",
    "bash",
    "gitignore",
    "haskell",
    "go",
    "python",
    "c",
    "cpp",
    "meson",
    "cmake",
    "make",
    "markdown",
    "nix",
    "lua",
    "rust",
  },
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  autotag = {
    enable = true,
  },
})
