#!/usr/bin/env bash

case $1 in
    i)
        pamixer --allow-boost -i5
        ;;
    d)
        pamixer --allow-boost -d5
        ;;
    t)
        pamixer -t
        ;;
esac

pkill -RTMIN+10 dwmblocks
